version: '3.4'

services:
  outboxpattern:
    image: ${DOCKER_REGISTRY-}outboxpattern
    container_name: api-outboxpattern
    build:
      context: .
      dockerfile: OutboxPattern/Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"